# Generated by Django 5.2.11 on 2026-03-02 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_alter_orderitem_menu_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
